#!/usr/bin/env python3

import os
import json
from glob import glob
from textwrap import dedent

def main():
    fp = glob("/autograder/submission/*.json")[0]

    with open(fp) as f:
        subm = json.load(f)

    output = {}
    output["tests"] = []

    for att in subm:
        output["tests"].append({
            "name": os.path.splitext(att["lecture_file"])[0],
            "score": int(att["attended"]),
            "output": dedent(f"""\
                Lecture: {os.path.splitext(att["lecture_file"])[0]}
                Attended in-person: {att["attended_in_person"]}
                Quiz score (%): {att["quiz_score"]}
                -------------------------------------------------------
                Earned attendance credit: {att["attended"]}
            """)
        })

    with open("/autograder/results/results.json", "w+") as f:
        json.dump(output, f, indent=2)

if __name__ == "__main__":
    main()
